In [1]:
# Group By
# “Group similar rows together and perform calculations.”
import pandas as pd

data = {
    "Name": ["Akshil", "Raj", "Priya", "Neha", "Aman"],
    "Department": ["IT", "HR", "IT", "HR", "IT"],
    "Salary": [50000, 40000, 60000, 45000, 55000],
    "Age": [22, 25, 23, 24, 26]
}

df = pd.DataFrame(data)

print(df)

     Name Department  Salary  Age
0  Akshil         IT   50000   22
1     Raj         HR   40000   25
2   Priya         IT   60000   23
3    Neha         HR   45000   24
4    Aman         IT   55000   26

In [2]:
df.groupby("Department")["Salary"].mean()

Department
HR    42500.0
IT    55000.0
Name: Salary, dtype: float64

In [3]:
# Multiple Aggregations
df.groupby("Department")["Salary"].agg(["mean", "max", "min"])

               mean    max    min
Department
HR          42500.0  45000  40000
IT          55000.0  60000  50000

In [4]:
# Count employees in each department
df.groupby("Department")["Name"].count()

Department
HR    2
IT    3
Name: Name, dtype: int64

In [5]:
# Sum
df.groupby("Department")["Salary"].sum()

Department
HR     85000
IT    165000
Name: Salary, dtype: int64

In [6]:
# Multiple Columns Grouping
df.groupby(["Department", "Age"])["Salary"].mean()

Department  Age
HR          24     45000.0
            25     40000.0
IT          22     50000.0
            23     60000.0
            26     55000.0
Name: Salary, dtype: float64

In [7]:
# Sort Values after GroupBy
df.groupby("Department")["Salary"].mean().sort_values(ascending=False)

Department
IT    55000.0
HR    42500.0
Name: Salary, dtype: float64

In [8]:
# GroupBy Multiple Columns
df.groupby("Department")[["Salary", "Age"]].mean()

             Salary        Age
Department
HR          42500.0  24.500000
IT          55000.0  23.666667

In [9]:
# Custom Function in GroupBy
def salary_range(x):
    return x.max() - x.min()

df.groupby("Department")["Salary"].apply(salary_range)

Department
HR     5000
IT    10000
Name: Salary, dtype: int64

In [10]:
# IMPORTANT AGGREGATION FUNCTIONS
# Function	Meaning
# mean()	Average
# sum()	Total
# count()	Number of rows
# max()	Maximum
# min()	Minimum
# std()	Standard deviation
# median()	Middle value
# nunique()	Unique count

In [12]:
# MERGE

# Combine two DataFrames using common columns.
employees = pd.DataFrame({
    "EmpID": [1, 2, 3],
    "Name": ["Akshil", "Raj", "Priya"]
})

print(employees)

   EmpID    Name
0      1  Akshil
1      2     Raj
2      3   Priya

In [13]:
salary = pd.DataFrame({
    "EmpID": [1, 2, 4],
    "Salary": [50000, 60000, 70000]
})

print(salary)

   EmpID  Salary
0      1   50000
1      2   60000
2      4   70000

In [14]:
# 1. INNER MERGE 
pd.merge(employees, salary, on="EmpID", how="inner")

   EmpID    Name  Salary
0      1  Akshil   50000
1      2     Raj   60000

In [15]:
# LEFT MERGE
pd.merge(employees, salary, on="EmpID", how="left")

   EmpID    Name   Salary
0      1  Akshil  50000.0
1      2     Raj  60000.0
2      3   Priya      NaN

In [16]:
# RIGHT MERGE
pd.merge(employees, salary, on="EmpID", how="right")

   EmpID    Name  Salary
0      1  Akshil   50000
1      2     Raj   60000
2      4     NaN   70000

In [17]:
# OUTER MERGE
pd.merge(employees, salary, on="EmpID", how="outer")

   EmpID    Name   Salary
0      1  Akshil  50000.0
1      2     Raj  60000.0
2      3   Priya      NaN
3      4     NaN  70000.0

In [18]:
# INNER → matching only

# LEFT  → all left + matching right

# RIGHT → all right + matching left

# OUTER → everything

In [19]:
# Merge on Different Column Names
df1 = pd.DataFrame({
    "id": [1, 2],
    "name": ["A", "B"]
})

df2 = pd.DataFrame({
    "emp_id": [1, 2],
    "salary": [50000, 60000]
})

pd.merge(df1, df2,
         left_on="id",
         right_on="emp_id")

   id name  emp_id  salary
0   1    A       1   50000
1   2    B       2   60000

In [21]:
# Function	Definition
# mean()	Calculates average value
# sum()	Calculates total value
# count()	Counts number of rows/items
# agg()	Applies multiple functions together
# apply()	Applies custom function
# reset_index()	Converts index into normal column
# inner	Keeps only matching rows from both tables
# left	Keeps all rows from left table
# right	Keeps all rows from right table
# outer	Keeps all rows from both tables
# left_on	Specifies left table merge column
# right_on	Specifies right table merge column
# suffixes	Adds suffix to duplicate column names after merge